### ISSUE TITLE
Segmenting multiple sentences in quotes

### ISSUE THREAD

**Issue by slatteryjim** [diasks2/pragmatic_segmenter#13]
I noticed the following is treated as one sentence:
```
"This is a sentence. And this is another one. And this is the third."
```
Is that by design? When not surrounded by double quotes, it is split into 3 sentences.

I was segmenting sentences in a novel, and entire paragraphs were surrounded in double quotes and got treated as one huge sentence.

**Comment by diasks2** [comment]
Hi,

Yes, this was by design. My main purpose (use case) for creating this gem was for segmenting for a translation application. If you check the README under **Background** you'll see a section that talks about some of the opinionated stances this segmenter takes. That is one of them. 

As you state, I think for novels and poems and the like you run into issues where there is a large block of text (maybe whole paragraphs) that do not get segmented. However, for most other translations (technical manuals, web pages) I think it is better to keep it as one segment for the purposes of translation memory.

The other issue that comes into play is that if we do segment your example into 3 segments, what do we do with the quotes? In essence you end up with some hanging quotes, which personally bugs me because then it is not a grammatically correct sentence:
`"This is a sentence.`  
`And this is another one.`  
`And this is the third."`

**Comment by slatteryjim** [comment]
Thanks, that does make sense. In my case, I'm trying to extract a list of all the sentences in a novel.

I guess if the segmenter returns a "sentence" that is fully surrounded by double-quotes, I can trim off the double-quotes and run the segmenter again on that result. That should give me a decent list of standalone sentences that exist in the text.

**Comment by diasks2** [comment]
Also be sure to check for quotations that fall in the middle of a segment - for example (i.e. you'll miss some if you only search for segments with quotes at the beginning and end):

```Then he said, "Hello. How are you?" as he faced the stranger.```

**Comment by ghnp5** [comment]
I wonder if we could have an option to change that behavior, as a parameter in the constructor? :)
