### ISSUE TITLE
pragmatic_segmenter installing problem 

### ISSUE THREAD

**Issue by sevilaybayatli** [diasks2/pragmatic_segmenter#69]
gem install pragmatic_segmenter
Successfully installed pragmatic_segmenter-0.3.22
Parsing documentation for pragmatic_segmenter-0.3.22
Done installing documentation for pragmatic_segmenter after 0 seconds
1 gem installed

But it does not install:
sevilay@sevilay-linux:~$ apt-cache policy pragmatic_segmenter
N: Unable to locate package pragmatic_segmenter

Please anyone could tell me what is the problem?

**Comment by alextsui05** [comment]
Hi @sevilaybayatli, I'm responding to your comment here: https://github.com/diasks2/pragmatic_segmenter/pull/68#issuecomment-762462583

It seems like your system should have the gem installed properly. `gem install` is different from `apt install`, so instead of using `apt-cache`, use `gem list` to look for the package.

As for your code, if you re-run it now, I think you should have no error when you require pragmatic_segmenter in your code.

**Comment by sevilaybayatli** [comment]
Hi @alextsui05, 
:~$ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.8)
did_you_mean (1.0.0)
io-console (0.4.5)
json (1.8.3)
minitest (5.8.3)
net-telnet (0.1.1)
power_assert (0.2.6)
pragmatic (0.1.1)
pragmatic_segmenter (0.3.22, 0.3.18)
psych (2.0.17)
rake (10.4.2)
rdoc (4.2.1)
test-unit (3.1.5)
unicode (0.4.4.4)
It seems I have pragmatic-segmenter, I don't understand why  got that error then:(

**Comment by diasks2** [comment]
Is this solved with the newest version: https://github.com/diasks2/pragmatic_segmenter/pull/68 ?

**Comment by sevilaybayatli** [comment]
Yeah it solved.

**Comment by sevilaybayatli** [comment]
Solved!
